name: ci

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

jobs:
  cargo-test:
    name: cargo test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
        - continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - uses: dsherret/rust-toolchain-file@v1
    - name: Run cargo test
      continue-on-error: ${{ matrix.continue-on-error || false }}
      run: |
        cargo test --workspace --no-default-features
    - run: cargo clippy
      if: contains(matrix.os, 'ubuntu')
    - run: cargo fmt --all -- --check
      if: contains(matrix.os, 'ubuntu')
